# Generated by Django 4.2.1 on 2023-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='dfggg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
